### ISSUE TITLE
Cause St2 Workflow to Fail if Jenkins Job Fails

### ISSUE THREAD

**Issue by rdancel001** [StackStorm-Exchange/stackstorm-jenkins#17]
Is there a mechanism in this pack where if the Jenkins Job fails, it should cause the St2 action to also fail? (return code != 0)

I'd like to set up a workflow where if the jenkins.build_job action triggers a job that fails, it should return a fail and therefore stop the workflow with an err. I set up a jenkins job where it's just got a build step of "exit 1" which causes the job to fail, but the workflow continues on saying it succeeded.

**Comment by rush-skills** [comment]
Hello. I am not a user of the `jenkins` pack, but I am assuming you are running into this issue because you are relying on the success of the action to <en-queue/start the job>, rather the success of the job itself. 

This is common in StackStorm, as success from an action only implies that the action itself was executed successfully from StackStorm (runner) PoV, but doesn't make an async action report errors later down the line. 

A fix would be to add another step to your workflow after the `jenkins.build_job` action, that then runs `jenkins.get_job_info` on the job returned from the first action, and use the status returned by `get_job_info` to decide if the job was a failure or not and handle the cases accordingly.

**Comment by arms11** [comment]
I agree with @rush-skills . The action `jenkins.build_job` does not wait/give result of the job completion. It's a fire/forget which is an underlying behavior of the exposed Jenkins library/API. This should be done by polling another method either in your action/workflow step. I am not a direct user of the pack, but I do use the same library that it uses and it's the behavior I have experienced, so not necessarily pack limitation per se.

**Comment by rdancel001** [comment]
Ok. Give me some time to try configuring the get_job_info and see if I can work with that to have the workflow fail/pass based on its return.

**Comment by rdancel001** [comment]
So I have been trying a few different methods and thus far I'm not getting anywhere good. Below is the output of the jenkins.get_job_info action. 

```json
{
  "stdout": "",
  "stderr": "",
  "exit_code": 0,
  "result": {
    "_class": "hudson.model.FreeStyleProject",
    "actions": [
      {
        "_class": "hudson.model.ParametersDefinitionProperty",
        "parameterDefinitions": [
          {
            "_class": "hudson.model.StringParameterDefinition",
            "defaultParameterValue": {
              "_class": "hudson.model.StringParameterValue",
              "value": "Jenkins-Test-VM"
            },
            "description": "Name of the VM to deploy.",
            "name": "VMToProvision",
            "type": "StringParameterDefinition"
          }
        ]
      },
      {},
      {},
      {},
      {},
      {},
      {},
      {
        "_class": "hudson.plugins.jobConfigHistory.JobConfigHistoryProjectAction"
      },
      {},
      {},
      {},
      {
        "_class": "org.jenkinsci.plugins.displayurlapi.actions.JobDisplayAction"
      },
      {},
      {
        "_class": "com.cloudbees.plugins.credentials.ViewCredentialsAction"
      }
    ],
    "description": "",
    "displayName": "test-vm-build",
    "displayNameOrNull": null,
    "fullDisplayName": "test-vm-build",
    "fullName": "test-vm-build",
    "name": "test-vm-build",
    "url": "http://*****:8080/job/test-vm-build/",
    "buildable": true,
    "builds": [
      {
        "_class": "hudson.model.FreeStyleBuild",
        "number": 62,
        "url": "http://*****:8080/job/test-vm-build/62/"
      },
      {
        "_class": "hudson.model.FreeStyleBuild",
        "number": 61,
        "url": "http://*****:8080/job/test-vm-build/61/"
      },
      {
        "_class": "hudson.model.FreeStyleBuild",
        "number": 60,
        "url": "http://*****:8080/job/test-vm-build/60/"
      },
      {
        "_class": "hudson.model.FreeStyleBuild",
        "number": 59,
        "url": "http://*****:8080/job/test-vm-build/59/"
      },
      {
        "_class": "hudson.model.FreeStyleBuild",
        "number": 58,
        "url": "http://*****:8080/job/test-vm-build/58/"
      },
      {
        "_class": "hudson.model.FreeStyleBuild",
        "number": 57,
        "url": "http://*****:8080/job/test-vm-build/57/"
      },
      {
        "_class": "hudson.model.FreeStyleBuild",
        "number": 56,
        "url": "http://*****:8080/job/test-vm-build/56/"
      },
      {
        "_class": "hudson.model.FreeStyleBuild",
        "number": 55,
        "url": "http://*****:8080/job/test-vm-build/55/"
      },
      {
        "_class": "hudson.model.FreeStyleBuild",
        "number": 54,
        "url": "http://*****:8080/job/test-vm-build/54/"
      },
      {
        "_class": "hudson.model.FreeStyleBuild",
        "number": 53,
        "url": "http://*****:8080/job/test-vm-build/53/"
      },
      {
        "_class": "hudson.model.FreeStyleBuild",
        "number": 47,
        "url": "http://*****:8080/job/test-vm-build/47/"
      }
    ],
    "color": "red",
    "firstBuild": {
      "_class": "hudson.model.FreeStyleBuild",
      "number": 47,
      "url": "http://*****:8080/job/test-vm-build/47/"
    },
    "healthReport": [
      {
        "description": "Build stability: All recent builds failed.",
        "iconClassName": "icon-health-00to19",
        "iconUrl": "health-00to19.png",
        "score": 0
      }
    ],
    "inQueue": false,
    "keepDependencies": false,
    "lastBuild": {
      "_class": "hudson.model.FreeStyleBuild",
      "number": 62,
      "url": "http://*****:8080/job/test-vm-build/62/"
    },
    "lastCompletedBuild": {
      "_class": "hudson.model.FreeStyleBuild",
      "number": 62,
      "url": "http://*****:8080/job/test-vm-build/62/"
    },
    "lastFailedBuild": {
      "_class": "hudson.model.FreeStyleBuild",
      "number": 62,
      "url": "http://*****:8080/job/test-vm-build/62/"
    },
    "lastStableBuild": {
      "_class": "hudson.model.FreeStyleBuild",
      "number": 47,
      "url": "http://*****:8080/job/test-vm-build/47/"
    },
    "lastSuccessfulBuild": {
      "_class": "hudson.model.FreeStyleBuild",
      "number": 47,
      "url": "http://*****:8080/job/test-vm-build/47/"
    },
    "lastUnstableBuild": null,
    "lastUnsuccessfulBuild": {
      "_class": "hudson.model.FreeStyleBuild",
      "number": 62,
      "url": "http://*****:8080/job/test-vm-build/62/"
    },
    "nextBuildNumber": 63,
    "property": [
      {
        "_class": "hudson.plugins.jira.JiraProjectProperty"
      },
      {
        "_class": "jenkins.model.BuildDiscarderProperty"
      },
      {
        "_class": "com.sonyericsson.rebuild.RebuildSettings"
      },
      {
        "_class": "hudson.model.ParametersDefinitionProperty",
        "parameterDefinitions": [
          {
            "_class": "hudson.model.StringParameterDefinition",
            "defaultParameterValue": {
              "_class": "hudson.model.StringParameterValue",
              "name": "VMToProvision",
              "value": "Jenkins-Test-VM"
            },
            "description": "Name of the VM to deploy.",
            "name": "VMToProvision",
            "type": "StringParameterDefinition"
          }
        ]
      },
      {
        "_class": "hudson.plugins.jobConfigHistory.JobLocalConfiguration"
      }
    ],
    "queueItem": null,
    "concurrentBuild": false,
    "disabled": false,
    "downstreamProjects": [],
    "labelExpression": null,
    "scm": {
      "_class": "hudson.scm.NullSCM"
    },
    "upstreamProjects": []
  }
} 
```
Here's the jenkins.get_job_info config in the workflow.

```yaml
get_run_status:
    action: jenkins.get_job_info
    next:
      - do:
          - Post_Exec_Msg_Passed
        when: <% result().lastBuild.number %> == <% result().lastSuccessfulBuild.number %>
      - do:
          - Post_Exec_Msg_Failed
        when: <%result().lastBuild.number %> == <% result().lastUnsuccessfulBuild.number %>
    input:
      log_level: DEBUG
      project: test-vm-build
```

**Comment by rdancel001** [comment]
I got something working now. Kinda redid it a little, but it works properly now. 

```yaml
get_run_status:
    action: jenkins.get_job_info
    input:
      log_level: DEBUG
      project: <% ctx('jenkins_job_to_trigger') %>
    next:
      - do:
          - get_job_status
        publish:
          - grabbed_build_num: <% result().result.lastBuild.number %>

get_job_status:
    action: jenkins.get_build_info
    input:
      log_level: DEBUG
      number: <% ctx().grabbed_build_num %>
      project: <% ctx('jenkins_job_to_trigger') %>
    next:
      - do:
          - Post_Exec_Msg_Passed
        when: <% result().result.result != "FAILURE" %>
      - do:
          - Post_Exec_Msg_Failed
        when: <% result().result.result = "FAILURE" %> 
```
